#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
  StopTask(displayDiagnostics);
  eraseDisplay();
  return;
}

void checkSticks1(TJoystick joystick){
	static char buffer1[20];

	sprintf(buffer1, "x1 %d  y1 %d", joystick.joy1_x1, joystick.joy1_y1);
	nxtDisplayTextLine(2, buffer1);
	sprintf(buffer1, "x2 %d  y2 %d", joystick.joy1_x2, joystick.joy1_y2);
	nxtDisplayTextLine(3, buffer1);
}

void checkSticks2(TJoystick joystick){
	static char buffer1[20];

	sprintf(buffer1, "x1 %d  y1 %d", joystick.joy2_x1, joystick.joy2_y1);
	nxtDisplayTextLine(5, buffer1);
	sprintf(buffer1, "x2 %d  y2 %d", joystick.joy2_x2, joystick.joy2_y2);
	nxtDisplayTextLine(6, buffer1);
}

task main()
{
  initializeRobot();

  waitForStart();

  while (true)
  {
  	nxtDisplayTextLine(1, "Checking sticks...");
	  getJoystickSettings(joystick);
	  checkSticks1(joystick);
	  checkSticks2(joystick);
  }
}
