#pragma config(Sensor, S1,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
SensorType[S1] = sensorHiTechnicTouchMux; // Configure the sensor.

while (true)
{
int nButtonsMask;

//
// The sensor value is a 4-bit map indicating which of the possible four
// touch sensors are pressed.
//
nButtonsMask = SensorValue[S1];

if (nButtonsMask & 0x01) {
   nxtDisplayTextLine(1, "Btn 1: Pressed");
   nxtDisplayRICFile(0,0,"buttonOn.ric");
} else {
   nxtDisplayTextLine(1, "Btn 1:");
   nxtDisplayRICFile(0,0,"buttonOff.ric");
}

if (nButtonsMask & 0x02)
nxtDisplayTextLine(2, "Btn 2: Pressed");
else
nxtDisplayTextLine(2, "Btn 2:");

if (nButtonsMask & 0x04)
nxtDisplayTextLine(3, "Btn 3: Pressed");
else
nxtDisplayTextLine(3, "Btn 3:");

if (nButtonsMask & 0x08)
nxtDisplayTextLine(4, "Btn 4: Pressed");
else
nxtDisplayTextLine(4, "Btn 4:");
wait1Msec(100);
}
}
